# Generated by Django 3.1.2 on 2020-10-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, unique=True, verbose_name='消息内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
            ],
        ),
    ]
