# Generated by Django 3.1.2 on 2020-10-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '消息通知管理'},
        ),
    ]
