# Generated by Django 3.1.2 on 2020-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201019_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='banner/', verbose_name='Banner图链接')),
            ],
            options={
                'verbose_name_plural': 'Banner图',
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '消息通知'},
        ),
    ]
