# Generated by Django 3.1.2 on 2020-10-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banner_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Banner图标题'),
        ),
    ]
