# Generated by Django 3.1.2 on 2020-10-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201019_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='source',
            new_name='resource',
        ),
    ]
