# Generated by Django 3.1.2 on 2020-10-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201019_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='media/banner/', verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='resource',
            field=models.CharField(max_length=100, null=True, verbose_name='链接到的url'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(max_length=100, verbose_name='消息内容'),
        ),
    ]
