# Generated by Django 3.1.2 on 2020-10-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201019_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='标题'),
        ),
    ]
