# Generated by Django 3.1.2 on 2020-10-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201019_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='书名')),
                ('image', models.ImageField(max_length=200, null=True, upload_to='media/book/', verbose_name='图书封面链接')),
                ('order_address', models.CharField(max_length=100, null=True, verbose_name='下单地址')),
                ('coupon_address', models.CharField(max_length=100, null=True, verbose_name='领券地址')),
                ('is_coupon', models.BooleanField(default=False, null=True, verbose_name='是否有优惠券')),
                ('current_price', models.FloatField(default=0, null=True, verbose_name='现价')),
                ('current_face_price', models.IntegerField(default=0, null=True, verbose_name='优惠券面值')),
                ('monthly_sale', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Python参考用书',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '轮播图'},
        ),
    ]
