# Generated by Django 3.1.2 on 2020-10-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201019_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='monthly_sale',
            field=models.IntegerField(default=0, null=True, verbose_name='月销'),
        ),
    ]
