# Generated by Django 3.1.2 on 2020-10-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201019_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '参考用书'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='media/banner/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='media/book/', verbose_name='图书封面'),
        ),
    ]
