# Generated by Django 3.1.2 on 2020-10-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201019_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='boo_store',
            field=models.CharField(max_length=20, null=True, verbose_name='书店'),
        ),
    ]
