# Generated by Django 3.1.2 on 2020-10-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_book_boo_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flag',
            field=models.CharField(max_length=3, null=True, verbose_name='位置标记'),
        ),
    ]
