# Generated by Django 3.1.2 on 2020-10-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_book_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='boo_store',
            new_name='book_store',
        ),
    ]
