# Generated by Django 3.1.2 on 2020-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201020_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_price',
            field=models.FloatField(null=True, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='monthly_sale',
            field=models.IntegerField(null=True, verbose_name='月销'),
        ),
    ]
