# Generated by Django 3.1.2 on 2020-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201020_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_face_price',
            field=models.FloatField(default=0, null=True, verbose_name='优惠券面值'),
        ),
    ]
