# Generated by Django 3.1.2 on 2020-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201020_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_face_price',
            field=models.IntegerField(default=0, null=True, verbose_name='优惠券面值'),
        ),
    ]
